"""Initial commit

Revision ID: 628c5105c808
Revises: 933083f9fddb
Create Date: 2024-10-18 17:13:48.281198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '628c5105c808'
down_revision = '933083f9fddb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(), nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
