"""Created Park, Hotel, Beach tables

Revision ID: aa9ea9d5862d
Revises: 
Create Date: 2024-10-17 09:47:12.210167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa9ea9d5862d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('destinations') as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=False, server_default="0"))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('destinations', schema=None) as batch_op:
        batch_op.drop_column('rating')
        batch_op.drop_column('address')

    # ### end Alembic commands ###
